### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by kylehamilton** [rmetaverse/metaverse#4]
@mjwestgate should write some

**Comment by mcguinlu** [comment]
@mjwestgate I'd be happy to take a stab at these if it would help?

Either way, I was looking into this and I've linked the CONTRIBUTING.md files for some tidyverse and other (exemplar) packages below so that whoever ends up writing can quickly reference them!

**Tidyverse**
ggplot2 -> https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md
dplyr -> https://github.com/tidyverse/dplyr/blob/master/.github/CONTRIBUTING.md

**Other (recommended by GitHub as exemplars)**
puppet -> https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md
factory_bot_rails -> https://github.com/thoughtbot/factory_bot_rails/blob/master/CONTRIBUTING.md

**Comment by kylehamilton** [comment]
I'm also willing to help since this might have a few facets to it. Some quick things I like include the part in dplyr on how to contribute fixes to typos. I think as we go on having some instructions for people who are just getting used to GitHub and R is important. Also reminding people about a code of conduct is important #3 . If I get sometime later today I'll throw together some sort of outline.
